"""add kyc progress fields

Revision ID: 7c4e5f3a8b2c
Revises: 661fc11f0974
Create Date: 2026-07-31 05:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7c4e5f3a8b2c'
down_revision: Union[str, None] = '661fc11f0974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_reports', sa.Column('progress_step', sa.String(length=50), nullable=True))
    op.add_column('kyc_reports', sa.Column('progress_percent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_reports', 'progress_percent')
    op.drop_column('kyc_reports', 'progress_step')
    # ### end Alembic commands ###
